a=int(input('Введите переменную a : '))
b=int(input('Введите переменную b : '))
d=int(input('Введите переменную d : '))
c=int(input('Введите переменную c : '))
k=int(input('Введите переменную k : '))
f=int(input('Введите переменную f : '))
prim1=(a**2/b**2+c**2*a**2)/(a+b+c*(k-a/b))+c+(k/b-k/a)*c
print('Пример 1 =', prim1)
prim2=((a**2-b**3-c**3*a**2)*(b-c+c*(k-d/b**3))-(k/b-k/a)*c)**2-20000
print('Пример 2 =', prim2)
prim3=1-a*b**c-a*(b**2-c**2)+(b-c+a)*(12+b)/(c-a)
print('Пример 3 =', prim3)
prim4=a-b*c**d**3+(c**5-a**2)/a+f**3*(a-213)
print('Пример 4 =', prim4)