import math as m
a=int(input('Введите число a '))
b=int(input('Введите число b '))
c=int(input('Введите число c '))
k=int(input('Введите число k '))
d=int(input('Введите число d '))
f=int(input('Введите число f '))
s=abs((a**2/b**2+c**2*a**2)/(a+b+c*(k-a/b**3))+c+(k/b+k/a)*c)
print('S1 = ',s)
s=abs(((a**2-b**3-c**3*a**2)*(b-c+c*(k-d/d**3))-(k/b-k/a)*c)**2-20000)
print('S2 = ',s)
s=abs((1-a*b**c-a*(b**2-c**2)+(b-c+a)*(12+b)/(c-a)))
print('S3 = ',s)
s=abs((a-b*c*d**3+(c**5-a**2)/a+f**3*(a-213)))
print('S4 = ',s)
